name: Compile templates

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest version from master branch
        uses: actions/checkout@v2
      - name: Compile NCR Abstract
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tests/ncr_abstract/ncr_abstract_template.tex
          pre_compile: "sh install.sh"
          work_in_root_file_dir: true
      - name: Compile NCR Proceedings
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tests/ncr_proceedings/ncr_proceedings_template.tex
          work_in_root_file_dir: true
      - name: Check pdf file
        run: |
          file tests/ncr_abstract/ncr_abstract_template.pdf | grep -q ' PDF '
          file tests/ncr_proceedings/ncr_proceedings_template.pdf | grep -q ' PDF '
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: Tests
          path: tests
   
